{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "84ea165b-dfe8-4c2a-880e-73f60b7c53ec",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Campus Lost & Found\n",
      "1. Report Lost Item\n",
      "2. Report Found Item\n",
      "3. Search Items\n",
      "4. Find Possible Match\n",
      "5. View All Reports\n",
      "6. Update Item Status\n",
      "7. View Statistics\n",
      "8. Exit\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Enter your choice:  1\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Report Lost Item\n"
     ]
    },
    {
     "name": "stdin",
     "output_type": "stream",
     "text": [
      "Your name:  mayank\n",
      "Item name:  rolls royce cullian\n",
      "Category:  cars, vehicles\n"
     ]
    }
   ],
   "source": [
    "import json\n",
    "import string\n",
    "\n",
    "items = []\n",
    "next_id = 1\n",
    "\n",
    "\n",
    "class Item:\n",
    "    def __init__(self, item_id, name, item_type, title, category,\n",
    "                 location, description, date, status=\"Active\"):\n",
    "        self.item_id = item_id\n",
    "        self.name = name\n",
    "        self.item_type = item_type\n",
    "        self.title = title\n",
    "        self.category = category\n",
    "        self.location = location\n",
    "        self.description = description\n",
    "        self.date = date\n",
    "        self.status = status\n",
    "\n",
    "    def show(self):\n",
    "        print(\"-\" * 40)\n",
    "        print(\"ID:\", self.item_id)\n",
    "        print(\"Reported by:\", self.name)\n",
    "        print(\"Type:\", self.item_type)\n",
    "        print(\"Item:\", self.title)\n",
    "        print(\"Category:\", self.category)\n",
    "        print(\"Location:\", self.location)\n",
    "        print(\"Description:\", self.description)\n",
    "        print(\"Date:\", self.date)\n",
    "        print(\"Status:\", self.status)\n",
    "\n",
    "\n",
    "def clean_words(text):\n",
    "    text = text.lower()\n",
    "    text = text.translate(str.maketrans(\"\", \"\", string.punctuation))\n",
    "    return set(text.split())\n",
    "\n",
    "\n",
    "def match_score(lost_item, found_item):\n",
    "    score = 0\n",
    "\n",
    "    if lost_item.category.lower() == found_item.category.lower():\n",
    "        score += 30\n",
    "\n",
    "    if lost_item.location.lower() == found_item.location.lower():\n",
    "        score += 25\n",
    "\n",
    "    lost_words = clean_words(lost_item.description)\n",
    "    found_words = clean_words(found_item.description)\n",
    "\n",
    "    common_words = lost_words.intersection(found_words)\n",
    "\n",
    "    if lost_words:\n",
    "        keyword_score = min(\n",
    "            35,\n",
    "            int((len(common_words) / len(lost_words)) * 35)\n",
    "        )\n",
    "        score += keyword_score\n",
    "\n",
    "    if lost_item.date == found_item.date:\n",
    "        score += 10\n",
    "\n",
    "    return score, common_words\n",
    "\n",
    "\n",
    "def add_item(item_type):\n",
    "    global next_id\n",
    "\n",
    "    print(\"\\nReport\", item_type, \"Item\")\n",
    "\n",
    "    name = input(\"Your name: \").strip()\n",
    "    title = input(\"Item name: \").strip()\n",
    "    category = input(\"Category: \").strip()\n",
    "    location = input(\"Location: \").strip()\n",
    "    description = input(\"Description: \").strip()\n",
    "    date = input(\"Date (DD-MM-YYYY): \").strip()\n",
    "\n",
    "    if not name or not title or not category or not location or not description:\n",
    "        print(\"Please enter all required details.\")\n",
    "        return\n",
    "\n",
    "    item = Item(\n",
    "        next_id,\n",
    "        name,\n",
    "        item_type,\n",
    "        title,\n",
    "        category,\n",
    "        location,\n",
    "        description,\n",
    "        date\n",
    "    )\n",
    "\n",
    "    items.append(item)\n",
    "    next_id += 1\n",
    "\n",
    "    print(\"Report saved successfully.\")\n",
    "    print(\"Your Item ID is:\", item.item_id)\n",
    "\n",
    "\n",
    "def search_items():\n",
    "    keyword = input(\"\\nEnter a word to search: \").strip().lower()\n",
    "\n",
    "    found = False\n",
    "\n",
    "    for item in items:\n",
    "        text = (\n",
    "            item.title + \" \" +\n",
    "            item.category + \" \" +\n",
    "            item.location + \" \" +\n",
    "            item.description\n",
    "        ).lower()\n",
    "\n",
    "        if keyword in text:\n",
    "            item.show()\n",
    "            found = True\n",
    "\n",
    "    if not found:\n",
    "        print(\"No matching reports found.\")\n",
    "\n",
    "\n",
    "def find_matches():\n",
    "    item_id = input(\"\\nEnter Lost Item ID: \").strip()\n",
    "\n",
    "    if not item_id.isdigit():\n",
    "        print(\"Enter a valid numeric ID.\")\n",
    "        return\n",
    "\n",
    "    lost_item = None\n",
    "\n",
    "    for item in items:\n",
    "        if item.item_id == int(item_id) and item.item_type == \"Lost\":\n",
    "            lost_item = item\n",
    "            break\n",
    "\n",
    "    if lost_item is None:\n",
    "        print(\"Lost item not found.\")\n",
    "        return\n",
    "\n",
    "    matches = []\n",
    "\n",
    "    for item in items:\n",
    "        if item.item_type == \"Found\" and item.status == \"Active\":\n",
    "            score, common_words = match_score(lost_item, item)\n",
    "\n",
    "            if score >= 40:\n",
    "                matches.append((item, score, common_words))\n",
    "\n",
    "    matches.sort(key=lambda x: x[1], reverse=True)\n",
    "\n",
    "    if not matches:\n",
    "        print(\"No possible matches found.\")\n",
    "        return\n",
    "\n",
    "    print(\"\\nPossible Matches\")\n",
    "\n",
    "    for item, score, common_words in matches:\n",
    "        print(\"-\" * 40)\n",
    "        print(\"Found Item ID:\", item.item_id)\n",
    "        print(\"Item:\", item.title)\n",
    "        print(\"Location:\", item.location)\n",
    "        print(\"Match Score:\", str(score) + \"%\")\n",
    "\n",
    "        if common_words:\n",
    "            print(\"Common words:\", \", \".join(common_words))\n",
    "\n",
    "\n",
    "def view_reports():\n",
    "    if not items:\n",
    "        print(\"\\nNo reports available.\")\n",
    "        return\n",
    "\n",
    "    print(\"\\nAll Reports\")\n",
    "\n",
    "    for item in items:\n",
    "        item.show()\n",
    "\n",
    "\n",
    "def update_status():\n",
    "    item_id = input(\"\\nEnter Item ID: \").strip()\n",
    "\n",
    "    if not item_id.isdigit():\n",
    "        print(\"Enter a valid numeric ID.\")\n",
    "        return\n",
    "\n",
    "    for item in items:\n",
    "        if item.item_id == int(item_id):\n",
    "            status = input(\n",
    "                \"Enter new status (Active/Resolved): \"\n",
    "            ).strip().title()\n",
    "\n",
    "            if status not in [\"Active\", \"Resolved\"]:\n",
    "                print(\"Status must be Active or Resolved.\")\n",
    "                return\n",
    "\n",
    "            item.status = status\n",
    "            print(\"Status updated.\")\n",
    "            return\n",
    "\n",
    "    print(\"Item ID not found.\")\n",
    "\n",
    "\n",
    "def statistics():\n",
    "    lost = 0\n",
    "    found = 0\n",
    "    active = 0\n",
    "    resolved = 0\n",
    "\n",
    "    for item in items:\n",
    "        if item.item_type == \"Lost\":\n",
    "            lost += 1\n",
    "        else:\n",
    "            found += 1\n",
    "\n",
    "        if item.status == \"Active\":\n",
    "            active += 1\n",
    "        else:\n",
    "            resolved += 1\n",
    "\n",
    "    print(\"\\nCampus Lost & Found Statistics\")\n",
    "    print(\"Total reports:\", len(items))\n",
    "    print(\"Lost reports:\", lost)\n",
    "    print(\"Found reports:\", found)\n",
    "    print(\"Active reports:\", active)\n",
    "    print(\"Resolved reports:\", resolved)\n",
    "\n",
    "\n",
    "def main():\n",
    "    while True:\n",
    "        print(\"\\nCampus Lost & Found\")\n",
    "        print(\"1. Report Lost Item\")\n",
    "        print(\"2. Report Found Item\")\n",
    "        print(\"3. Search Items\")\n",
    "        print(\"4. Find Possible Match\")\n",
    "        print(\"5. View All Reports\")\n",
    "        print(\"6. Update Item Status\")\n",
    "        print(\"7. View Statistics\")\n",
    "        print(\"8. Exit\")\n",
    "\n",
    "        choice = input(\"Enter your choice: \").strip()\n",
    "\n",
    "        if choice == \"1\":\n",
    "            add_item(\"Lost\")\n",
    "\n",
    "        elif choice == \"2\":\n",
    "            add_item(\"Found\")\n",
    "\n",
    "        elif choice == \"3\":\n",
    "            search_items()\n",
    "\n",
    "        elif choice == \"4\":\n",
    "            find_matches()\n",
    "\n",
    "        elif choice == \"5\":\n",
    "            view_reports()\n",
    "\n",
    "        elif choice == \"6\":\n",
    "            update_status()\n",
    "\n",
    "        elif choice == \"7\":\n",
    "            statistics()\n",
    "\n",
    "        elif choice == \"8\":\n",
    "            print(\"Thank you for using Campus Lost & Found.\")\n",
    "            break\n",
    "\n",
    "        else:\n",
    "            print(\"Please choose a number from 1 to 8.\")\n",
    "\n",
    "\n",
    "main()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e25db10b-66c2-4312-979f-35585d516d1d",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.14.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
